### PR TITLE
fix(validator): drop unused ProgressReporter kwargs + use f-strings

### PR DESCRIPTION
**Pull request by that-guy-wade**
## Description

Two regressions from #133 surfaced live on staging once the SDK lock fix (#134) landed and the validator started actually reading `inference_token`:

1. `ProgressReporter()` was called with `inference_provider=` and `inference_base_url=` kwargs that its `__init__` never accepted. Every claimed eval crashed with `TypeError: ProgressReporter.__init__() got an unexpected keyword argument 'inference_provider'` before the sandbox could launch. The reasoning judge inside ProgressReporter is still Chutes-only and gates on `chutes_access_token`, so neither field was ever consumed downstream. OR-aware judging is a separate piece of work — drop the kwargs.

2. The new `"Using miner's %s token..."` log line used `%`-style formatting, but bittensor's logger adapter prepends/appends its own tokens via the same args list, eating the first/last positional args before stdlib `%`-substitution sees them. Result: `TypeError: not enough arguments for format string` (with `inference_provider` and `eval_run_id_str` already consumed by the adapter). Switch to f-strings to bypass it. Also fixed two adjacent log lines in the same block.

## Changes Made

- Drop `inference_provider=` / `inference_base_url=` kwargs from the `ProgressReporter()` call in `subnet/validator/main.py:782`
- Convert three `logging.info`/`logging.warning` calls in the same function from `%s`-args style to f-strings

## Issue Link

- Related to: ORO-1039 (multi-provider routing)

### Manual Testing

Confirmed on staging validator `5ChkSz9gbUAp...` (i-0017e8a2f060e9a5c):
- Pre-fix: `069fc007-...` claimed → `TypeError: ProgressReporter.__init__() got an unexpected keyword argument 'inference_provider'` → eval failed before sandbox
- Pre-fix: format-string error logged on every claim once `inference_token` was present in the response

Will verify post-merge that the next claim launches the sandbox cleanly and OR inference flows through the proxy.

**Test Results:** N/A — minimal kwarg + log formatting fix.

### Automated Testing

**Test Command(s):**
```bash
python3 -c "import ast; ast.parse(open('subnet/validator/main.py').read())"
```

## Documentation

- [ ] README updated
- [ ] Code comments added/updated
- [ ] API documentation updated
- [ ] Configuration documentation updated
- [ ] Other documentation updated (please specify):

**Documentation Changes:** N/A
## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published and merged

## Additional Notes

Once merged, tag a new patch version so Watchtower picks up `:latest` on staging and the next agent submission can drive a real sandbox + OR inference call through the proxy.

### CODE REVIEW

**Review by shardi-b — APPROVED** [review]
Approved. No issues found during code review.

**Review summary:**
- Verified `ProgressReporter.__init__` signature only accepts `chutes_access_token`, not `inference_provider`/`inference_base_url` — removing those kwargs is the correct fix for the `TypeError`
- f-string conversion is appropriate given bittensor logger adapter consuming positional args before stdlib `%`-substitution
- Changes are minimal and scoped correctly to the regression from #133
